### PR TITLE
Increased dependency constraints to Magento 2.4.1 and PHP 7.4

### PR DESCRIPTION
**Pull request by erfanimani**
Please hold off on merging, I'm still in the process of testing although so far everything seems to work OK!

### CODE REVIEW

**Comment by erfanimani** [comment]
@scottsb this is OK from my end, so feel free to merge if you're happy with it!

Thanks

**Comment by erfanimani** [comment]
@scottsb FYI, we're now using this with 2.4.2

**Comment by jaywilliams** [comment]
We're upgrading to PHP 7.4, so getting this merged into an official release would make things easier.

**Comment by scottsb** [comment]
Merged indirectly via #12. Closing.

**Comment by scottsb** [comment]
@erfanimani @jaywilliams I can't tag you directly on #13, so tagging you here to make you aware. Let me know if either of you would be interested in taking over this extension going forward.

**Comment by jaywilliams** [comment]
Hey Scott, as long as the company I work for is actively using this extension, I don't mind maintaining bugfixes, after all, I'll probably be finding & fixing them myself anyway, so might as well share those fixes with the community.

Easiest option would be to just add me as a maintainer of the repo, but if you don't want it hosted on /ripenecommerce/, we can look into what it would take to smoothly switch it to a new namespace.

**Comment by erfanimani** [comment]
Hey @scottsb, I'm happy to be added as a maintainer. One of my clients is using this extension so I would be maintaining it anyway.

**Comment by scottsb** [comment]
@erfanimani @jaywilliams I've invited both of you as maintainers to this repository. That should allow you to do whatever you need to do with making updates while it still lives here under "ripenecommerce." If at some point there's a need to do anything that you can't do with that role, we could move it elsewhere.

**Pull request closed without merging**
